### ISSUE TITLE
Header title not displayed using react-navigation 1.0.0-beta.7

### ISSUE THREAD

**Issue by zash80** [FruitieX/react-navigation-native-base#1]
Using react-navigation 1.0.0-beta.7, the header title text isn't displayed anymore.

**Comment by FruitieX** [comment]
Here's the offending commit: https://github.com/react-community/react-navigation/commit/e650f341e35fbb87f265c354019f5431cf09e2fc

I have a fix coming in the [bugfix/beta7](https://github.com/FruitieX/react-navigation-native-base/tree/bugfix/beta7) branch.

**Comment by zash80** [comment]
Verified fix is working using branch bugfix/beta7 ("react-navigation-native-base": "github:FruitieX/react-navigation-native-base#bugfix/beta7").

**Comment by FruitieX** [comment]
Thanks for testing. I will do some additional tests and make sure it works on both platforms, then release a new npm version.

**Comment by FruitieX** [comment]
Should be fixed in react-navigation-native-base@1.0.0-beta.7.1.

Closing.
