### ISSUE TITLE
Back button not displayed using react-navigation@1.0.0-beta.7

### ISSUE THREAD

**Issue by zash80** [FruitieX/react-navigation-native-base#2]
Using react-navigation@1.0.0-beta.7 the back button isn't displayed anymore. Maybe also related to #1

**Comment by zash80** [comment]
#1

**Comment by FruitieX** [comment]
Indeed, same problem. Fix coming.

**Comment by FruitieX** [comment]
Should be fixed in react-navigation-native-base@1.0.0-beta.7.1.

Closing.
