### ISSUE TITLE
Roadmap for tabnavigator?

### ISSUE THREAD

**Issue by IniZio** [FruitieX/react-navigation-native-base#4]
Really nice integration with react-navigation and native base, is there a roadmap for the tab navigator though? I am working on an app and will need to use tab component. For now I am using the native-base tab component

**Comment by FruitieX** [comment]
Hi, I'm not actively working on it at the moment. For the moment I can recommend using the react-navigation tab bar and style it according to your native base theme variables.

**Comment by IniZio** [comment]
Thanks for the clarification, think I will stick with native-base's tab component for now
